name = "MyTestPkg"
uuid = "4f6ce0f5-5ade-49bc-a8cb-9d3f52535077"
authors = ["Pietro Panizza"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
